<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> 
  <xacro:include filename="$(find chapt9_urdf_description)/urdf/fishbot/common_inertial.xacro"/>
  <xacro:macro name="base_xacro" params="length radius">
    <link name="base_footprint" />

    <link name="base_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> 
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="white">
            <color rgba="1.0 1.0 1.0 0.9"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> 
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="white">
            <color rgba="1.0 1.0 1.0 0.9"/>
        </material>
      </collision>
      <!-- 惯性-->
      <xacro:cylinder_inertia m="1.0"  r="${radius}" h="${length}"/>
    </link>
    <joint name="base_link_joint" type="fixed">
      <origin xyz="0.0 0.0 ${length/2+0.03}" rpy="0.0 0.0 0.0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>

    <!-- gazebo中的颜色 ： 未生效 -->
    <!-- <gazebo reference="base_link" >
      <material>Gazebo/White</material>
    </gazebo> -->

  </xacro:macro>


  </robot>